### ISSUE TITLE
meta data error

### ISSUE THREAD

**Issue by YoungbinHa** [xeonsim/opensea-upload-with-recaptcha-solution#1]
I got the error below when it fills meta data. I'm using the metadata one.

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//tbody[@class="AssetTraitsForm--body"]/tr[last()]/td[1]/div/div/input"}

**Comment by xeonsim** [comment]
Can you tell me witch line it is?

**Comment by YoungbinHa** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\young\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "uploadopensea_metadata.py", line 387, in main_program_loop
    input1 = driver.find_element_by_xpath('//tbody[@class="AssetTraitsForm--body"]/tr[last()]/td[1]/div/div/input')
  File "C:\Users\young\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath 
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\young\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\young\anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\young\anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response     
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//tbody[@class="AssetTraitsForm--body"]/tr[last()]/td[1]/div/div/input"}
  (Session info: chrome=98.0.4758.102)

**Comment by xeonsim** [comment]
I have updated some codes vanyou try and contact me and tell if it works

**Comment by YoungbinHa** [comment]
Just check that out, and I got new error when I run python uploadopensea_metadata.py.

  File "uploadopensea_metadata.py", line 397
    driver.find_element_by_xpath('//button[text()="Save"]').click()
                                                                                                     ^
IndentationError: unindent does not match any outer indentation level

**Comment by xeonsim** [comment]
It is previos versión now it is changed

**Comment by xeonsim** [comment]
Does it fill metadata well now?

**Comment by YoungbinHa** [comment]
Now I got weird error. Seems it is not the code prob I guess. When I download metamask on the program, I got error "Download interrupted" and not able to add extension which is weird. I will figure it out myself and try it tmmr. Thanks man.

**Comment by kaikecloss** [comment]
guys I'm still having this problem

> Hi, I'm using the metadata one here.
> 
> But, I got the error below when it fills meta data. It successfully adds the first metadata attributes, but when it adds second one, the program stops.
> 
> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//tbody[@Class="AssetTraitsForm--body"]/tr[last()]/td[1]/div/div/input"}

guys I'm still having this problem. How can I solve this?
