### ISSUE TITLE
Recaptcha seems to be getting hung up.

### ISSUE THREAD

**Issue by mlewis412-git** [xeonsim/opensea-upload-with-recaptcha-solution#21]
![image](https://user-images.githubusercontent.com/73501943/164786081-f016fcd3-3ac5-42c9-ac99-9d964da276a2.png)

I dont know if its something in the setup. Is any one getting stuck on captcha ? It just returns false false then errors out after. Doesnt seem to try to input the captcha.

**Comment by thevileo** [comment]
Figured this one out. The code needs to be changed 
Search for "recaptcha-anchor"  in openseaupload (it probably has div value of 1.. Change it to the following:

check_button = WebDriverWait(driver, 10).until(ExpectedConditions.presence_of_element_located((By.XPATH,'//*[@id="recaptcha-anchor"]/div[4]')))

**Comment by mlewis412-git** [comment]
Seems to be issue with the click on line 179 of openseaupload.py, verified the xpath is correct still. just not checking the box.


        try:
                check_button = WebDriverWait(driver, 10).until(ExpectedConditions.presence_of_element_located((By.XPATH,'//*[@id="recaptcha-anchor"]/div[1]')))
                time.sleep(random.randint(2,3))
                time.sleep(random.randint(2,3))
                check_button.click()

**Comment by mlewis412-git** [comment]
Line 166 needs to be changed to 
       displayOk = check_exists_by_xpath('/html/body/div[10]/div/div/div/section/div')
Now the click occurs. 
Once I got past that, It trys to solve first captcha then fails:

Start creating NFT Dudilz1
step 1
step 2
step 3
True
[INFO] Audio src: https://recaptcha.net/recaptcha/api2/payload?p=06AGdBq27Gndj-nxhEnFyX_m4Ku1_OTSUZKhpnoeDW6-Yi2i4JJZyGM8E_qtVMFob5m8ny_9JjjUP3Tr1J6mZszTQwJglnW7R213C7PjGo_uvjxQWWYPtvsIQ4ZPRY3qriTyfK72A444G0_sgQz8nFIgFWrwiEf3NQXhoLts-W4D7eufR9m7PluMl7TgGhBdh4EJRZ3DXVV1IJ&k=6LfpJ2geAAAAAKSEXNL5Yycd7IFWslDvGwuAtz9P
[INFO] Recaptcha Passcode: number changes
False

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Administrator\Desktop\opensea-upload-with-recaptcha-solution-main\openseaupload.py", line 369, in main_program_loop
    wait_xpath('//*[@id="__next"]/div[1]/main/div/div/div[1]/div/span[2]/a')
  File "C:\Users\Administrator\Desktop\opensea-upload-with-recaptcha-solution-main\openseaupload.py", line 151, in wait_xpath
    WebDriverWait(driver,20).until(ExpectedConditions.presence_of_element_located((By.XPATH, code)))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by mlewis412-git** [comment]
It appears to be validintg the audio .. But when the captcha is not solved correctly, its timesout now and does not attempt again

**Comment by maximedrn** [comment]
Hello, if you still have problems with this repository, I advise you to look at my [code](https://github.com/maximedrn/opensea-automatic-bulk-upload-and-sale). It solves reCAPTCHAs and is up to date unlike this repository which has not been maintained for 3 months.
